Session12
Hyperbolic4183/YumemiWeather-session12 pull request #8
Opened 2021-08-11 12:36 UTC by Hyperbolic4183

## 行ったこと
- SPMによるエラーに対して適切なハンドリングが行われるようにした
- フォアグランドに戻った時にクラッシュするバグを直した
- 複数の非同期処理が終わった後にインジケータが終了するように修正した。
- エラーが起きた時にインジケータが周り続けるバグを直した。

## 懸念点
- showIndicator(while processings) は時間に揺らぎのある複数の処理を同時におこない、処理が全て終了した時にインジケータのアニメーションをストップする関数であるが、このような関数のベストプラクティスがあれば知りたい。

2021-08-11 15:25 UTC, ykws requested changes
### Summary

不具合4件中2件発見 🎉 

1. SPMによるエラーに対して適切なハンドリングが行われるようにした 🤔 
2. フォアグランドに戻った時にクラッシュするバグを直した 👍  
3. 複数の非同期処理が終わった後にインジケータが終了するように修正した 🙅 
4. エラーが起きた時にインジケータが周り続けるバグを直した 👍  

---

1. SPM とは何を指していますでしょうか？
2. 不具合の指摘はばっちりです！　問題も解消されています。より適切な変更方法があるので、インラインコメントを参考に調べてみてください。
3. 災害情報の表示は非同期処理ではないので、 **複数の非同期処理** とはなっていないです。よって不具合とはカウントしません。
4. 不具合の指摘はばっちりです！　問題も解消されています。エラーの扱いが適切かどうか確認をお願いします。

不具合としてはあと2つあります。

---

それとコミットメッセージに関して気になったので補足です。

- 1行目が対応内容の要約
- 2行目は空白、
- 3行目以降に詳細及び、 Issue 番号と対応状況（ refs or fixes ）

となっていると見やすいです。

が、プロジェクトによっては 1行目に Issue 番号を prefix とするルールもあるので、
リポジトリで統一できていれば良いです。

ただし、プロジェクトでは Issue なしの変更は認めていないこともあるのでこのルールが適用しやすいですが、
Issue なしの変更も許容すると、 1行目に Issue とするのは、一貫性を保ちづらいので、
3行目以降の詳細に含めるのが無難です。今回の PR でも混ざっていたので気になりました。

2021-08-11 15:25 UTC, ykws commented on Example/Example/UI/Weather/Base.lproj/Weather.storyboard
> -<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="16096" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
![ask-badge](https://img.shields.io/badge/review-ask-blue.svg)

UI に不具合はありましたか？

2021-08-11 15:25 UTC, ykws commented on Example/Example/Model/WeatherModel.swift
> +            completion(.failure(.invalidParameterError))
![ask-badge](https://img.shields.io/badge/review-ask-blue.svg)

`.invalidParameterError` を `WeatherError` の `switch` と分けているのは何か理由がありますか？

2021-08-11 15:25 UTC, ykws commented on Example/Example/UI/Weather/WeatherViewController.swift
> +            loadWeather()
![ask-badge](https://img.shields.io/badge/review-ask-blue.svg)

こう変更できてしまうので、そもそもブロック処理を指定する Observer の登録が不自然に見えるので、別の登録方法で実現できそうか調べてみてください。

2021-08-12 00:49 UTC, Hyperbolic4183 commented on Example/Example/Model/WeatherModel.swift
> +            completion(.failure(.invalidParameterError))
これdo{}内の
```
let requestJson = try jsonString(from: request)
let responseJson = try YumemiWeather.syncFetchWeather(requestJson)
let response = try self.response(from: responseJson)
```
で吐かれるエラーの属するenumが異なっているので、分けざるを得なくなってしまった感じです。
こういう時、どういう対応をすべきでしょうか？

2021-08-12 00:51 UTC, Hyperbolic4183 commented on Example/Example/UI/Weather/Base.lproj/Weather.storyboard
> -<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="16096" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
ありません。
変えたつもりなかったのにコミットしてしまってました(*_*)

2021-08-12 00:55 UTC, Hyperbolic4183 commented
@ykws 
SPMは外部SwiftPackgeManagerのつもりでした。もしかしたら4とかぶっているかもしれません🙇‍♂️

2021-08-12 08:01 UTC, ykws commented
> SPMは外部SwiftPackgeManagerのつもりでした

ですよね。 SPM の差分がコミットにないようだったので、コミット漏れでしょうか？

2021-08-12 08:02 UTC, ykws commented on Example/Example/UI/Weather/Base.lproj/Weather.storyboard
> -<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="16096" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
不具合の修正と関係のない変更は元に戻してみてください。

2021-08-12 08:10 UTC, ykws commented on Example/Example/Model/WeatherModel.swift
> +            completion(.failure(.invalidParameterError))
YumemiWeather.syncFetchWeather でエラーとなった場合、常に WeatherError の invalidParameterError として扱うのが適切でしょうか？

2021-09-17 07:29 UTC, Hyperbolic4183 commented
# 行ったこと(9/17)
1 フォアグランドに戻った時にクラッシュするバグを直した(前回確認済み)
2 エラーが起きた時にインジケータが周り続けるバグを直した(前回確認済み)
3 壊れていたテストを直した #10  <- New
4 エラーが起きた時に画面がクローズするバグを直した #12 

## 3
### 概要
テストが壊れていたので、WeatherViewControllerとviewの結合テストを書き直した。
WeatherViewControllerの単体テストも追加した。

#### 詳細
WeatherViewControllerでは、複数の処理が全て終わるまでインジケータを表示し続ける'showIndicator(processings: Void...)'を実装している。また、天気の画像の切り替えやエラーアラートの表示といった画面の更新を'WeatherHandler'構造体の'handle(from )'によって行っている。
'showIndicator(processings: Void...)'の内部でglobalQueueへの切り替えを、'WeatherHandler.handler'を呼び出す時にmainQueueへの切り替えを行っている。そのため、テストの際にはそれらを考慮する必要があるため、DI可能にした。

## 4
### 概要
エラーが起きてアラートのOKボタンが押された後、画面を閉じるのではなく、エラーが起きた時に画像を差し替えるようにした。

### 詳細
天気の情報の取得はエラーが起きるが、災害の情報の取得はエラーが起きない。しかし、天気のエラーが起きた時にViewがdismissされてしまうため、本来正常に表示されるはずの災害の情報が見れなくなっている。
この問題を解決するために、天気の情報の取得の失敗時には画像をエラー画像に差し替えるように変更した。

2021-09-17 14:50 UTC, novr commented on Example/Example/UI/Weather/QueueScheduler.swift
> +            DispatchQueue.main.async(group: group) {
[MUST] DispatchGroupはnil不可です
> group: The dispatch group to associate with the work item. This parameter cannot be NULL.
https://developer.apple.com/documentation/dispatch/dispatchqueue/2300095-async

2021-09-17 14:50 UTC, novr commented on Example/Example/UI/Root/RootViewController.swift
> +public extension StoryboardResourceWithInitialControllerType {
[IMO] RootViewControllerではなく共通の拡張なので別ファイルで定義しましょう

2021-09-17 14:50 UTC, novr commented on Example/Example/UI/Weather/WeatherViewController.swift
> +    init?(coder: NSCoder, weatherModel: WeatherModel, disasterModel: DisasterModel = DisasterModelImpl(), weatherHandler: WeatherHandler = .live, mainQueueScheduler: QueueScheduler = .main, globalQue
[NITS] 長くなりすぎる場合は適宜改行など
```suggestion
    init?(coder: NSCoder,
    	  weatherModel: WeatherModel,
    	  disasterModel: DisasterModel = DisasterModelImpl(),
    	  weatherHandler: WeatherHandler = .live,
    	  mainQueueScheduler: QueueScheduler = .main,
    	  globalQueueScheduler: QueueScheduler = .global) {
```

2021-09-17 14:50 UTC, novr commented on Example/Example/UI/Weather/WeatherViewController.swift
> +        self.isEnabled = !self.isEnabled
[NITS] use toggle()
```suggestion
        self.isEnabled.toggle()
```
https://developer.apple.com/documentation/swift/bool/2994863-toggle

2021-09-17 14:50 UTC, novr commented on Example/Example/UI/Weather/WeatherViewController.swift
> +        reloadButton.toggleEnabled()
[NITS] こちらでも十分意味は伝わるかと
```suggestion
        reloadButton.isEnabled.toggle()
```

2021-09-24 02:25 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/118228)

2021-09-24 02:26 UTC, novr commented on Example/Example/UI/Weather/QueueScheduler.swift
> +            DispatchQueue.main.async(group: group) {
async(group:qos:flags:execute:)はnil許容だった

2021-09-24 05:52 UTC, merged